"""discipline_models

Revision ID: 2e5d82bae124
Revises: 
Create Date: 2024-04-30 21:26:48.639022

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2e5d82bae124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('discipline_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_name', sa.String(length=100), nullable=False),
    sa.Column('icons', sa.TEXT(), nullable=True),
    sa.Column('slug', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discipline_name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_discipline_model_id'), 'discipline_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discipline_model_id'), table_name='discipline_model')
    op.drop_table('discipline_model')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
