"""user_model3

Revision ID: 31eb8609ffbf
Revises: 642b09a93091
Create Date: 2024-05-05 21:34:38.244633

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '31eb8609ffbf'
down_revision = '642b09a93091'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
