"""user_model2

Revision ID: 642b09a93091
Revises: f632ec14fe40
Create Date: 2024-05-05 16:12:08.680215

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '642b09a93091'
down_revision = 'f632ec14fe40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
