"""user_model45

Revision ID: ce6f2c5b3388
Revises: f552e04f90ee
Create Date: 2024-05-05 21:54:38.949311

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ce6f2c5b3388'
down_revision = 'f552e04f90ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
