"""user_model4

Revision ID: f552e04f90ee
Revises: 31eb8609ffbf
Create Date: 2024-05-05 21:36:32.490604

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f552e04f90ee'
down_revision = '31eb8609ffbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_address', table_name='users')
    op.create_index(op.f('ix_users_email_address'), 'users', ['email_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_address'), table_name='users')
    op.create_index('email_address', 'users', ['email_address'], unique=False)
    # ### end Alembic commands ###
