"""user_model

Revision ID: f632ec14fe40
Revises: 2e5d82bae124
Create Date: 2024-05-05 09:55:07.226491

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f632ec14fe40'
down_revision = '2e5d82bae124'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
